### ISSUE TITLE
simple example for auth access

### ISSUE THREAD

**Issue by yvess** [flimzy/kivik#192]
couldn't send a comment on your blog (Wordpress error)

A simple example in the doc for a basic auth example for couchdb would be great. Struggling a bit to get it working (golang newbie).

Should a simple connection string work like (basic auth):

    client, err := kivik.New(context.TODO(), "couch", "http://user:password@localhost:5984/")

**Comment by flimzy** [comment]
Thanks for the report!

The connection string you've provided should work, although it will attempt Cookie auth first, and fall back to basic auth only if cookie auth fails (perhaps due to a proxy filtering cookies).

This behavior is only documented in an internal code comment at the moment, and is subject to change in future versions (feedback welcome!) as Basic Auth seems to me like a reasonable default, and with fewer moving parts.

I'll try to update the wiki and godoc with this information.

Is connecting this way not working for you?

**Comment by yvess** [comment]
Tried it again with and without basic auth. I think the wiki code example isn't correct anymore.
I build my code like in the wiki:

    row, err := db.Get(context.TODO(), "cow")
    if err != nil {
        panic(err)
    }
    var cow Animal
    if err = row.Scan(&cow); err != nil {
        panic(err)
    }
    fmt.Printf("The cow says '%s'\n", cow.Greeting)

but it seems it should be 'row.ScanDoc()' instead of 'row.Scan()' than it works also with basic auth with my connection string.

**Comment by flimzy** [comment]
You are right, it should be `ScanDoc`. I will update it.

**Comment by flimzy** [comment]
I have updated the wiki [here](https://github.com/flimzy/kivik/wiki/Usage-Examples#authentication) and [here](https://github.com/flimzy/kivik/wiki/Usage-Examples#fetching-a-document) to address the points brought up in this issue.  Please let me know if any further clarification would be useful.
